# Generated by Django 4.1.3 on 2022-12-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportationComparison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_airport_code', models.CharField(max_length=500)),
                ('destination_airport_code', models.CharField(max_length=500)),
                ('departure', models.DateTimeField()),
                ('arrival', models.DateTimeField()),
                ('airline_code', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='tripoutput',
            name='flights',
            field=models.ManyToManyField(to='TransportationComparison.flight'),
        ),
    ]
